defaults:
  - base
  - _self_
logging:
  level: INFO
name: prova
seed: 17
device: cuda
'N': 100
H: 300
num_layers: 1
J_D: 0.5
max_steps: 7
init_mode: zeros
init_noise: 0.0
lambda_x: 0.0
lambda_y: 1000.0
lambda_l: 1.0
lambda_r: ${lambda_l}
lambda_internal: 1.0
lambda_fc: 1.0
lambda_wback_skip: []
lambda_wback: 0.5
lambda_input_skip:
- 2.0
lambda_input_output_skip: 0.0
lambda_wforth_skip: []
lambda_wforth: 1.0
fc_left: false
fc_right: false
fc_input: false
symmetric_W: false
double_dynamics: false
double_update: false
use_local_ce: false
beta_ce: 10.0
lambda_cylinder: null
num_epochs: 40
batch_size: 16
threshold:
- 0.75
- 3.0
lr_input_output_skip: 0.1
lr_input_skip: 0.03
lr_J: 0.03
lr_W: 0.1
lr_wforth_skip: 0.1
weight_decay_J: 0.005
weight_decay_W: 0.005
weight_decay_wforth_skip: 0.005
weight_decay_input_skip: 0.0
weight_decay_input_output_skip: 0.005
begin_curriculum: 1.0
p_curriculum: 0.5
eval_interval: 1
skip_representations: false
skip_couplings: false
skip_fields: false
data:
  dataset: mnist
  P: 6000
  P_eval: 1000
  synthetic:
    C: 10
    p: 0.35
    save_dir: data
  mnist:
    binarize: true
  cifar:
    binarize: true
    cifar10: true
  hm:
    C: 2
    D: 30
    L: 1
    width: 300
    binarize: true