defaults:
  - /base@_here_
  - _self_

name: 'prova'
seed: 42
device: 'cpu'
batch_size: 4

N: 500
num_layers: 5
J_D: 0.2
lambda_left: 2.0
lambda_right: 2.0
lambda_x: 5.0
lambda_y: 5.0

num_epochs: 10
max_steps: 10     # full sweeps over the network (relaxation)
lr: 0.003         # perceptron rule
threshold: 1.5    # perceptron rule
eval_interval: 1  # epochs
skip_final_eval: true

data:
  C: 10  # number of classes
  P: 100  # patterns per class
  p: 0.4
  save_dir: 'data'

hardcore_parallel: true