defaults:
  - /base@_here_
  - _self_
  - /data@_here_

name: 'prova'
seed: 42
device: 'cpu'
batch_size: 32

N: 500
num_layers: 5
J_D: 0.2
lambda_left: 2.0
lambda_right: 2.0
lambda_x: 5.0
lambda_y: 5.0

num_epochs: 10
max_steps: 10       # full sweeps over the network (relaxation)
lr: 0.012           # perceptron rule
threshold: 1.5      # perceptron rule
weight_decay: 0.0   # scaled by learning rate
eval_interval: 1    # epochs
skip_final_eval: true
