defaults:
  - /base@_here_
  - _self_
  - /data@_here_

# Experiment
name: 'prova'
seed: 123
device: 'cpu'

# Network and Relaxation
N: 1000
num_layers: 5
J_D: 0.2
max_steps: 5                                  # full sweeps over the network (relaxation)
lambda_left: [0, 2.0, 2.0, 2.0, 2.0, 1.0]   # first is lambda_x, last affects the readout layer
lambda_right: [4.0, 4.0, 4.0, 4.0, 1.0, 4.0]  # last is lambda_y, last but one affects the readout layer
fc: false

# Perceptron Rule
num_epochs: 10
batch_size: 16
lr: [0.1, 0.1, 0.1, 0.1, 0.1, 0.01, 0.01]           # scaled by typical weight size. last two are for W_back and W_forth
threshold: [2.5, 2.5, 2.5, 2.5, 2.5, 2.5]                     # perceptron rule. last is for readout layer
weight_decay: [0.001, 0.001, 0.001, 0.001, 0.001, 0.0, 0.0]   # scaled by learning rate. last two are for W_back and W_forth

# Evaluation
eval_interval: 1        # epochs
skip_final_eval: false