defaults:
  - /base@_here_
  - _self_

name: 'prova'
seed: 42

N: 500
num_layers: 5
sparse_readout: false
train_readout: true
J_D: 0.2
sparse_couplings: false
sparsity_level: 0.25     # fraction of active (asymmetric) synapses

lambda_left: 2.0
lambda_right: 2.0
lambda_x: 5.0
lambda_y: 5.0

num_epochs: 10
max_steps: 50   # full sweeps over the network (relaxation)
lr: 0.003       # perceptron rule
threshold: 1.5  # perceptron rule
eval_interval: 1

data:
  C: 10  # number of classes
  P: 10  # patterns per class
  p: 0.35
  save_dir: 'data'
